apiVersion: v1
kind: Secret
metadata:
  name: securesense-secrets
  namespace: securesense
type: Opaque
stringData:
  VIRUSTOTAL_API_KEY: "REPLACE_ME"
  ABUSEIPDB_API_KEY: "REPLACE_ME"
  HIBP: "REPLACE_ME"
  GROQ_API_KEY: "REPLACE_ME"
  
  JWT_SECRET_KEY: "REPLACE_ME"
  SECRET_KEY: "REPLACE_ME"
  
  DATABASE_URL: "REPLACE_ME"
  DATABASE_PASSWORD: "REPLACE_ME"
  
  SMTP_USERNAME: "REPLACE_ME"
  SMTP_PASSWORD: "REPLACE_ME"
  
  SLACK_WEBHOOK_URL: "REPLACE_ME"